export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE";

export const USERS_DATA_STATE_CHANGE = "USERS_DATA_STATE_CHANGE";
export const USERS_POSTS_STATE_CHANGE = "USERS_POSTS_STATE_CHANGE";
export const DELETE_FOLLOWING = "DELETE_FOLLOWING";
export const CLEAR_DATA = "CLEAR_DATA";
export const FETCH_ALL_USER = "FETCH_ALL_USER";
export const USER_LIKES_STATE_CHANGE = "USER_LIKES_STATE_CHANGE";
export const FETCH_ALL_FEEDS = "FETCH_ALL_FEEDS";
